[project]
name = "transformer-diy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.0.0",
    "ruff>=0.12.10",
    "tokenizers>=0.21.4",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
